[build-system]
requires = ["setuptools >= 40.9.0", "wheel", "oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
exclude = '''
(
  \.git
  | build
  | dist
)

'''
