{% set name = "satpy" %}
{% set version = "0.10.0a0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5bf73a870f886449a5ac1412dea2c3df6c185bba833bb87d0e7e0bb9187b758a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  git_url: https://github.com/pytroll/satpy.git
  git_rev: eb26f12435952d2bab94e761a7f284f1fcb30d33

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.4.1
    - pillow
    - pyresample >=1.10.0
    - trollsift
    - trollimage >=1.5.1
    - pykdtree
    - six
    - pyyaml
    - xarray >=0.10.1
    - dask >=0.17.1
    - h5py
    - netcdf4
    - pyspectral

test:
  imports:
    - satpy
    - satpy.composites
    - satpy.enhancements
    - satpy.readers
    - satpy.tests
    - satpy.tests.compositor_tests
    - satpy.tests.reader_tests
    - satpy.tests.writer_tests
    - satpy.writers
  requires:
    - behave
    - h5py
    - imageio
    - libtiff
    - netcdf4
    - pyhdf

about:
  home: https://github.com/pytroll/satpy
  license: GPL-3.0
  license_family: GPL3
  license_file: 'LICENSE.txt'
  summary: Meteorological processing package
  description: |
      Python package for reading and manipulating meteorological remote
      sensing data and writing it to various image and data file formats.
  doc_url: 'http://satpy.readthedocs.io/en/latest/'
  dev_url: 'https://github.com/pytroll/satpy'

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
