name: test-environment
channels:
  - conda-forge
dependencies:
  # limiting python due to ecmwflibs
  - python<=3.11
  - appdirs
  - defusedxml
  - Cython
  # until https://github.com/imageio/imageio/issues/1120 is solved we need to limit imageio and pyav
  - imageio<=2.35.1
  - av<14.0.0
  - matplotlib
  - numba
  - numpy
  - pyproj
  - pyshp
  - pyqt
  - pyqtgraph
  - pyqtwebengine
  - satpy
  - scikit-image
  - shapely
  - sqlalchemy
  - vispy
  ### Satpy-only Optional Deps
  - bottleneck
  - dask
  - donfig
  # 2.19.1 seems to cause library linking issues
  - eccodes>=2.20
  - cfgrib
  - fsspec
  - h5netcdf
  - h5py
  - hdf5plugin
  - netcdf4
  - pillow
  - pooch
  - pyhdf
  - pyresample
  - python-eccodes
  - python-geotiepoints
  - pyyaml
  - rasterio
  - rioxarray
  - xarray
  - zarr
  ### Development/Test dependencies
  - coveralls
  - coverage
  - codecov
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-qt
  - pip
  - sphinx
  ### Pip Dependencies
  - pip:
    - trollsift
    - trollimage
    - pyspectral
    - pyorbital
    - ecmwflibs
